# Site settings
title: Bearstouch Software
company_name: Bearstouch Software
email: mail@bearstouch.com
description: > # this means to ignore newlines until "baseurl:"
  Bearstouch Software is a Software company that supplies high quality software services, software testing,application development and support services.
keywords: software company, software companies, software developers,freelancer,software outsourcing,mobile development,backend development,high quality software,outsource software development, outsourced software development, offshore software development company, offshore development, software application development, software freelancer,software devel
#baseurl: "/website/" # the subpath of your site, e.g. /blog/
#url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
url: "http://www.bearstouch.com" # the base hostname & protocol for your site
twitter_username: bearstouch
github_username:  bearstouch

# Build settings
markdown: kramdown
address: 'mail@bearstouch.com'
copyright: Copyright © 2014 Bearstouch Software
main_slogan: We build,deliver and maintain software
secondary_slogan:  We are your right partner to deliver better and secure software solutions.
banner_setence1: Bespoke Software Development
banner_setence2: Mobile and backend Software solutions for your business
